#!/bin/bash

llama_cpp_version=prism-2026-9-21
clean=${clean:-f}

# This is expected to be cloned from https://github.com/PrismML-Eng/llama.cpp
llama_cpp_path=/t/llama.cpp-prism

if [[ "$1" == clean ]]; then
  clean=t
fi

# assumed llama.cpp is checked out to the desired tag at /t/llama.cpp

extra=
if [[ $clean == t ]]; then
  echo "Cleaning..."
  extra='--no-cache'
  podman image rm localhost/llama.cpp:latest localhost/llama.cpp:$llama_cpp_version
  podman image prune -f
fi

nice sudo /usr/bin/podman build $extra -v $llama_cpp_path:/workspace/llama.cpp -t llama.cpp:$llama_cpp_version -f Dockerfile

