#!/bin/bash

llama_cpp_version=v0.4.1
clean=${clean:-f}
llama_cpp_path=/t/llama.cpp

#llama_cpp_path=/t/ROCmFPX
if [[ "$1" == clean ]]; then
  clean=t
fi

# assumed llama.cpp is checked out to the desired tag at /t/llama.cpp

if [[ $clean == t ]]; then
  echo "Cleaning..."
  sudo podman image rm localhost/llama.cpp:latest
  sudo podman image prune -f
fi

#podman build -v $llama_cpp_path:/workspace/llama.cpp -t llama.cpp-cpu -f Dockerfile-cpu-only
nice sudo /usr/bin/podman build -v $llama_cpp_path:/workspace/llama.cpp -t llama.cpp:$llama_cpp_version -f Dockerfile

