#!/bin/bash

clean=${clean:-f}
llama_cpp_path=/t/llama.cpp
#llama_cpp_path=/t/ROCmFPX
if [[ "$1" == clean ]]; then
  clean=t
fi

# assumed llama.cpp is checked out to the desired tag at /t/llama.cpp

if [[ $clean == t ]]; then
  echo "Cleaning..."
  podman image rm localhost/llama.cpp:latest
  podman image prune -f
fi

#podman build -v $llama_cpp_path:/workspace/llama.cpp -t llama.cpp-cpu -f Dockerfile-cpu-only
nice sudo /usr/bin/podman build -v $llama_cpp_path:/workspace/llama.cpp -t llama.cpp -f Dockerfile

