FROM rocm/dev-ubuntu-24.04:7.2.4-complete

RUN apt-get update && apt-get install -y vim libcurl4-openssl-dev cmake git
WORKDIR /workspace/llama.cpp

#RUN pip install --upgrade -r requirements.txt --extra-index-url https://download.pytorch.org/rocm7.2 --break-system-packages
RUN pip install --upgrade -r requirements.txt --extra-index-url https://download.pytorch.org/cpu --break-system-packages

# because newer version breaks gemma4 for some reason
RUN pip install transformers==4.45.2 --force-reinstall --break-system-packages

# cpu only
RUN HIPCXX="$(hipconfig -l)/clang" HIP_PATH="$(hipconfig -R)" \
  cmake -S . -B build \
  -DGGML_HIP=OFF -DGGML_CUDA=OFF -DGGML_VULKAN=OFF -DGGML_METAL=OFF \
  -DCMAKE_BUILD_TYPE=Release -DLLAMA_CURL=ON \
  && cmake --build build --config Release -j$(nproc)

